# Generated by Django 2.1.4 on 2018-12-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='album_art',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='track',
            name='album_art_origin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(default='artist', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='media_query_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='media_type',
            field=models.CharField(default='audio', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='media_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='service',
            field=models.CharField(default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='track',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
