export const PLAY_TRACK = 'PLAY_TRACK'
export const PAUSE_TRACK = 'PAUSE_TRACK'
export const STOP_TRACK = 'STOP_TRACK'
export const NEXT_TRACK = 'NEXT_TRACK'
export const PREVIOUS_TRACK = 'PREVIOUS_TRACK'
export const CURRENT_TRACK = 'CURRENT_TRACK'
