# Generated by Django 2.1.4 on 2018-12-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20181207_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='service',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
